- name: Install and configure PostgreSQL
  hosts: web
  become: true
  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: true

    - name: Install Python PostgreSQL dependencies
      apt:
        name: python3-psycopg2
        state: present

    - name: Start PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Create internship_pg database
      shell: sudo -u postgres createdb internship_pg

    - name: Create intern_user with privileges
      shell: sudo -u postgres psql -c "CREATE USER intern_user WITH PASSWORD 'intern_pass'; GRANT ALL PRIVILEGES ON DATABASE internship_pg TO intern_user;"

    - name: Create users table
      shell: sudo -u postgres psql -d internship_pg -c "CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name TEXT);"

    - name: Insert sample data - Adarsh
      shell: sudo -u postgres psql -d internship_pg -c "INSERT INTO users (name) VALUES ('Adarsh');"

    - name: Insert sample data - Pearl Thought
      shell: sudo -u postgres psql -d internship_pg -c "INSERT INTO users (name) VALUES ('Pearl Thought');"

